// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: akademik.proto

package akademik_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MataKuliah struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                       // ID unik mata kuliah (misalnya UUID)
	KodeMk string `protobuf:"bytes,2,opt,name=kode_mk,json=kodeMk,proto3" json:"kode_mk,omitempty"` // Kode mata kuliah, contoh: IF101
	NamaMk string `protobuf:"bytes,3,opt,name=nama_mk,json=namaMk,proto3" json:"nama_mk,omitempty"` // Nama mata kuliah, contoh: Dasar Pemrograman
	Sks    int32  `protobuf:"varint,4,opt,name=sks,proto3" json:"sks,omitempty"`                    // Jumlah SKS
}

func (x *MataKuliah) Reset() {
	*x = MataKuliah{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MataKuliah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MataKuliah) ProtoMessage() {}

func (x *MataKuliah) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MataKuliah.ProtoReflect.Descriptor instead.
func (*MataKuliah) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{0}
}

func (x *MataKuliah) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MataKuliah) GetKodeMk() string {
	if x != nil {
		return x.KodeMk
	}
	return ""
}

func (x *MataKuliah) GetNamaMk() string {
	if x != nil {
		return x.NamaMk
	}
	return ""
}

func (x *MataKuliah) GetSks() int32 {
	if x != nil {
		return x.Sks
	}
	return 0
}

type Mahasiswa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // ID unik mahasiswa (misalnya UUID)
	Nim           string   `protobuf:"bytes,2,opt,name=nim,proto3" json:"nim,omitempty"`                                            // Nomor Induk Mahasiswa
	Nama          string   `protobuf:"bytes,3,opt,name=nama,proto3" json:"nama,omitempty"`                                          // Nama lengkap mahasiswa
	Jurusan       string   `protobuf:"bytes,4,opt,name=jurusan,proto3" json:"jurusan,omitempty"`                                    // Jurusan mahasiswa
	MataKuliahIds []string `protobuf:"bytes,5,rep,name=mata_kuliah_ids,json=mataKuliahIds,proto3" json:"mata_kuliah_ids,omitempty"` // Daftar ID mata kuliah yang diambil (ini adalah "edge")
	// Untuk menampilkan detail mata kuliah secara langsung, kita bisa tambahkan ini:
	// Namun, ini akan membuat pesan Mahasiswa lebih besar.
	// Alternatifnya, klien bisa memanggil RPC lain untuk mendapatkan detail MataKuliah.
	// Untuk contoh ini, kita akan coba isi melalui resolver di server jika diminta.
	DetailMataKuliah []*MataKuliah `protobuf:"bytes,6,rep,name=detail_mata_kuliah,json=detailMataKuliah,proto3" json:"detail_mata_kuliah,omitempty"`
}

func (x *Mahasiswa) Reset() {
	*x = Mahasiswa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mahasiswa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mahasiswa) ProtoMessage() {}

func (x *Mahasiswa) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mahasiswa.ProtoReflect.Descriptor instead.
func (*Mahasiswa) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{1}
}

func (x *Mahasiswa) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mahasiswa) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *Mahasiswa) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *Mahasiswa) GetJurusan() string {
	if x != nil {
		return x.Jurusan
	}
	return ""
}

func (x *Mahasiswa) GetMataKuliahIds() []string {
	if x != nil {
		return x.MataKuliahIds
	}
	return nil
}

func (x *Mahasiswa) GetDetailMataKuliah() []*MataKuliah {
	if x != nil {
		return x.DetailMataKuliah
	}
	return nil
}

type CreateMahasiswaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nim     string `protobuf:"bytes,1,opt,name=nim,proto3" json:"nim,omitempty"`
	Nama    string `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	Jurusan string `protobuf:"bytes,3,opt,name=jurusan,proto3" json:"jurusan,omitempty"`
}

func (x *CreateMahasiswaRequest) Reset() {
	*x = CreateMahasiswaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMahasiswaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMahasiswaRequest) ProtoMessage() {}

func (x *CreateMahasiswaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMahasiswaRequest.ProtoReflect.Descriptor instead.
func (*CreateMahasiswaRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMahasiswaRequest) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *CreateMahasiswaRequest) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *CreateMahasiswaRequest) GetJurusan() string {
	if x != nil {
		return x.Jurusan
	}
	return ""
}

type GetMahasiswaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SertakanDetailMataKuliah bool   `protobuf:"varint,2,opt,name=sertakan_detail_mata_kuliah,json=sertakanDetailMataKuliah,proto3" json:"sertakan_detail_mata_kuliah,omitempty"` // Flag untuk meminta detail mata kuliah
}

func (x *GetMahasiswaRequest) Reset() {
	*x = GetMahasiswaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMahasiswaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMahasiswaRequest) ProtoMessage() {}

func (x *GetMahasiswaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMahasiswaRequest.ProtoReflect.Descriptor instead.
func (*GetMahasiswaRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{3}
}

func (x *GetMahasiswaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMahasiswaRequest) GetSertakanDetailMataKuliah() bool {
	if x != nil {
		return x.SertakanDetailMataKuliah
	}
	return false
}

type UpdateMahasiswaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nim     string `protobuf:"bytes,2,opt,name=nim,proto3" json:"nim,omitempty"`
	Nama    string `protobuf:"bytes,3,opt,name=nama,proto3" json:"nama,omitempty"`
	Jurusan string `protobuf:"bytes,4,opt,name=jurusan,proto3" json:"jurusan,omitempty"`
}

func (x *UpdateMahasiswaRequest) Reset() {
	*x = UpdateMahasiswaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMahasiswaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMahasiswaRequest) ProtoMessage() {}

func (x *UpdateMahasiswaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMahasiswaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMahasiswaRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMahasiswaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMahasiswaRequest) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *UpdateMahasiswaRequest) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *UpdateMahasiswaRequest) GetJurusan() string {
	if x != nil {
		return x.Jurusan
	}
	return ""
}

type DeleteMahasiswaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMahasiswaRequest) Reset() {
	*x = DeleteMahasiswaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMahasiswaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMahasiswaRequest) ProtoMessage() {}

func (x *DeleteMahasiswaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMahasiswaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMahasiswaRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMahasiswaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMahasiswaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Bisa ditambahkan filter atau parameter paginasi di sini
	SertakanDetailMataKuliah bool `protobuf:"varint,1,opt,name=sertakan_detail_mata_kuliah,json=sertakanDetailMataKuliah,proto3" json:"sertakan_detail_mata_kuliah,omitempty"`
}

func (x *ListMahasiswaRequest) Reset() {
	*x = ListMahasiswaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMahasiswaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMahasiswaRequest) ProtoMessage() {}

func (x *ListMahasiswaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMahasiswaRequest.ProtoReflect.Descriptor instead.
func (*ListMahasiswaRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{6}
}

func (x *ListMahasiswaRequest) GetSertakanDetailMataKuliah() bool {
	if x != nil {
		return x.SertakanDetailMataKuliah
	}
	return false
}

type ListMahasiswaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaftarMahasiswa []*Mahasiswa `protobuf:"bytes,1,rep,name=daftar_mahasiswa,json=daftarMahasiswa,proto3" json:"daftar_mahasiswa,omitempty"`
}

func (x *ListMahasiswaResponse) Reset() {
	*x = ListMahasiswaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMahasiswaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMahasiswaResponse) ProtoMessage() {}

func (x *ListMahasiswaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMahasiswaResponse.ProtoReflect.Descriptor instead.
func (*ListMahasiswaResponse) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{7}
}

func (x *ListMahasiswaResponse) GetDaftarMahasiswa() []*Mahasiswa {
	if x != nil {
		return x.DaftarMahasiswa
	}
	return nil
}

type CreateMataKuliahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KodeMk string `protobuf:"bytes,1,opt,name=kode_mk,json=kodeMk,proto3" json:"kode_mk,omitempty"`
	NamaMk string `protobuf:"bytes,2,opt,name=nama_mk,json=namaMk,proto3" json:"nama_mk,omitempty"`
	Sks    int32  `protobuf:"varint,3,opt,name=sks,proto3" json:"sks,omitempty"`
}

func (x *CreateMataKuliahRequest) Reset() {
	*x = CreateMataKuliahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMataKuliahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMataKuliahRequest) ProtoMessage() {}

func (x *CreateMataKuliahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMataKuliahRequest.ProtoReflect.Descriptor instead.
func (*CreateMataKuliahRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMataKuliahRequest) GetKodeMk() string {
	if x != nil {
		return x.KodeMk
	}
	return ""
}

func (x *CreateMataKuliahRequest) GetNamaMk() string {
	if x != nil {
		return x.NamaMk
	}
	return ""
}

func (x *CreateMataKuliahRequest) GetSks() int32 {
	if x != nil {
		return x.Sks
	}
	return 0
}

type GetMataKuliahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMataKuliahRequest) Reset() {
	*x = GetMataKuliahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMataKuliahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMataKuliahRequest) ProtoMessage() {}

func (x *GetMataKuliahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMataKuliahRequest.ProtoReflect.Descriptor instead.
func (*GetMataKuliahRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{9}
}

func (x *GetMataKuliahRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListMataKuliahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListMataKuliahRequest) Reset() {
	*x = ListMataKuliahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMataKuliahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMataKuliahRequest) ProtoMessage() {}

func (x *ListMataKuliahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMataKuliahRequest.ProtoReflect.Descriptor instead.
func (*ListMataKuliahRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{10}
}

type ListMataKuliahResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaftarMataKuliah []*MataKuliah `protobuf:"bytes,1,rep,name=daftar_mata_kuliah,json=daftarMataKuliah,proto3" json:"daftar_mata_kuliah,omitempty"`
}

func (x *ListMataKuliahResponse) Reset() {
	*x = ListMataKuliahResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMataKuliahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMataKuliahResponse) ProtoMessage() {}

func (x *ListMataKuliahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMataKuliahResponse.ProtoReflect.Descriptor instead.
func (*ListMataKuliahResponse) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{11}
}

func (x *ListMataKuliahResponse) GetDaftarMataKuliah() []*MataKuliah {
	if x != nil {
		return x.DaftarMataKuliah
	}
	return nil
}

type DaftarkanMataKuliahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MahasiswaId  string `protobuf:"bytes,1,opt,name=mahasiswa_id,json=mahasiswaId,proto3" json:"mahasiswa_id,omitempty"`
	MataKuliahId string `protobuf:"bytes,2,opt,name=mata_kuliah_id,json=mataKuliahId,proto3" json:"mata_kuliah_id,omitempty"`
}

func (x *DaftarkanMataKuliahRequest) Reset() {
	*x = DaftarkanMataKuliahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaftarkanMataKuliahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaftarkanMataKuliahRequest) ProtoMessage() {}

func (x *DaftarkanMataKuliahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaftarkanMataKuliahRequest.ProtoReflect.Descriptor instead.
func (*DaftarkanMataKuliahRequest) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{12}
}

func (x *DaftarkanMataKuliahRequest) GetMahasiswaId() string {
	if x != nil {
		return x.MahasiswaId
	}
	return ""
}

func (x *DaftarkanMataKuliahRequest) GetMataKuliahId() string {
	if x != nil {
		return x.MataKuliahId
	}
	return ""
}

// Pesan kosong untuk RPC yang tidak mengembalikan data spesifik
type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_akademik_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akademik_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_akademik_proto_rawDescGZIP(), []int{13}
}

var File_akademik_proto protoreflect.FileDescriptor

var file_akademik_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x22, 0x60, 0x0a, 0x0a, 0x4d, 0x61,
	0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x6f, 0x64, 0x65,
	0x5f, 0x6d, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x6f, 0x64, 0x65, 0x4d,
	0x6b, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x6d, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x61, 0x4d, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x6b, 0x73, 0x22, 0xc7, 0x01, 0x0a,
	0x09, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61,
	0x74, 0x61, 0x5f, 0x6b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x49,
	0x64, 0x73, 0x12, 0x42, 0x0a, 0x12, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x61, 0x74,
	0x61, 0x5f, 0x6b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75,
	0x6c, 0x69, 0x61, 0x68, 0x52, 0x10, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x61, 0x74, 0x61,
	0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x22, 0x58, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x69, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61, 0x6e,
	0x22, 0x64, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x1b, 0x73, 0x65, 0x72, 0x74, 0x61,
	0x6b, 0x61, 0x6e, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x61, 0x74, 0x61, 0x5f,
	0x6b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x73, 0x65,
	0x72, 0x74, 0x61, 0x6b, 0x61, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x61, 0x74, 0x61,
	0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x22, 0x68, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x69, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x75, 0x72, 0x75, 0x73, 0x61, 0x6e,
	0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69,
	0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x3d, 0x0a, 0x1b, 0x73, 0x65, 0x72, 0x74, 0x61, 0x6b, 0x61, 0x6e, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x6d, 0x61, 0x74, 0x61, 0x5f, 0x6b, 0x75, 0x6c, 0x69, 0x61,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x18, 0x73, 0x65, 0x72, 0x74, 0x61, 0x6b, 0x61,
	0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61,
	0x68, 0x22, 0x57, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73,
	0x77, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x10, 0x64, 0x61,
	0x66, 0x74, 0x61, 0x72, 0x5f, 0x6d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e,
	0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x0f, 0x64, 0x61, 0x66, 0x74, 0x61,
	0x72, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x22, 0x5d, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x6f, 0x64, 0x65, 0x5f, 0x6d, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x6f, 0x64, 0x65, 0x4d, 0x6b, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x61, 0x5f, 0x6d, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x61, 0x6d, 0x61, 0x4d, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x6b, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c,
	0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x16, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x12, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x5f, 0x6d,
	0x61, 0x74, 0x61, 0x5f, 0x6b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x74, 0x61,
	0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x10, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x4d, 0x61,
	0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x22, 0x65, 0x0a, 0x1a, 0x44, 0x61, 0x66, 0x74,
	0x61, 0x72, 0x6b, 0x61, 0x6e, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x68, 0x61, 0x73, 0x69,
	0x73, 0x77, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61,
	0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x74,
	0x61, 0x5f, 0x6b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x49, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xd2, 0x05, 0x0a, 0x0f, 0x41, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x20, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d,
	0x69, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73,
	0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x6b, 0x61, 0x64,
	0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x42,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x1d,
	0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x68,
	0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73,
	0x77, 0x61, 0x12, 0x48, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x68, 0x61,
	0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x20, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d,
	0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x4c, 0x0a, 0x0f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12,
	0x20, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x1e, 0x2e, 0x61, 0x6b,
	0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73,
	0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x6b,
	0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x68, 0x61, 0x73,
	0x69, 0x73, 0x77, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68,
	0x12, 0x21, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d,
	0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x12, 0x45, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x12, 0x1e, 0x2e, 0x61, 0x6b, 0x61,
	0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c,
	0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x6b, 0x61,
	0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68,
	0x12, 0x53, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69,
	0x61, 0x68, 0x12, 0x1f, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x21, 0x44, 0x61, 0x66, 0x74, 0x61, 0x72, 0x6b,
	0x61, 0x6e, 0x4d, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x55, 0x6e, 0x74, 0x75,
	0x6b, 0x4d, 0x61, 0x68, 0x61, 0x73, 0x69, 0x73, 0x77, 0x61, 0x12, 0x24, 0x2e, 0x61, 0x6b, 0x61,
	0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x44, 0x61, 0x66, 0x74, 0x61, 0x72, 0x6b, 0x61, 0x6e, 0x4d,
	0x61, 0x74, 0x61, 0x4b, 0x75, 0x6c, 0x69, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x2e, 0x4d, 0x61, 0x68, 0x61,
	0x73, 0x69, 0x73, 0x77, 0x61, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2f, 0x61, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x6b, 0x5f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_akademik_proto_rawDescOnce sync.Once
	file_akademik_proto_rawDescData = file_akademik_proto_rawDesc
)

func file_akademik_proto_rawDescGZIP() []byte {
	file_akademik_proto_rawDescOnce.Do(func() {
		file_akademik_proto_rawDescData = protoimpl.X.CompressGZIP(file_akademik_proto_rawDescData)
	})
	return file_akademik_proto_rawDescData
}

var file_akademik_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_akademik_proto_goTypes = []interface{}{
	(*MataKuliah)(nil),                 // 0: akademik.MataKuliah
	(*Mahasiswa)(nil),                  // 1: akademik.Mahasiswa
	(*CreateMahasiswaRequest)(nil),     // 2: akademik.CreateMahasiswaRequest
	(*GetMahasiswaRequest)(nil),        // 3: akademik.GetMahasiswaRequest
	(*UpdateMahasiswaRequest)(nil),     // 4: akademik.UpdateMahasiswaRequest
	(*DeleteMahasiswaRequest)(nil),     // 5: akademik.DeleteMahasiswaRequest
	(*ListMahasiswaRequest)(nil),       // 6: akademik.ListMahasiswaRequest
	(*ListMahasiswaResponse)(nil),      // 7: akademik.ListMahasiswaResponse
	(*CreateMataKuliahRequest)(nil),    // 8: akademik.CreateMataKuliahRequest
	(*GetMataKuliahRequest)(nil),       // 9: akademik.GetMataKuliahRequest
	(*ListMataKuliahRequest)(nil),      // 10: akademik.ListMataKuliahRequest
	(*ListMataKuliahResponse)(nil),     // 11: akademik.ListMataKuliahResponse
	(*DaftarkanMataKuliahRequest)(nil), // 12: akademik.DaftarkanMataKuliahRequest
	(*EmptyResponse)(nil),              // 13: akademik.EmptyResponse
}
var file_akademik_proto_depIdxs = []int32{
	0,  // 0: akademik.Mahasiswa.detail_mata_kuliah:type_name -> akademik.MataKuliah
	1,  // 1: akademik.ListMahasiswaResponse.daftar_mahasiswa:type_name -> akademik.Mahasiswa
	0,  // 2: akademik.ListMataKuliahResponse.daftar_mata_kuliah:type_name -> akademik.MataKuliah
	2,  // 3: akademik.AkademikService.CreateMahasiswa:input_type -> akademik.CreateMahasiswaRequest
	3,  // 4: akademik.AkademikService.GetMahasiswa:input_type -> akademik.GetMahasiswaRequest
	4,  // 5: akademik.AkademikService.UpdateMahasiswa:input_type -> akademik.UpdateMahasiswaRequest
	5,  // 6: akademik.AkademikService.DeleteMahasiswa:input_type -> akademik.DeleteMahasiswaRequest
	6,  // 7: akademik.AkademikService.ListMahasiswa:input_type -> akademik.ListMahasiswaRequest
	8,  // 8: akademik.AkademikService.CreateMataKuliah:input_type -> akademik.CreateMataKuliahRequest
	9,  // 9: akademik.AkademikService.GetMataKuliah:input_type -> akademik.GetMataKuliahRequest
	10, // 10: akademik.AkademikService.ListMataKuliah:input_type -> akademik.ListMataKuliahRequest
	12, // 11: akademik.AkademikService.DaftarkanMataKuliahUntukMahasiswa:input_type -> akademik.DaftarkanMataKuliahRequest
	1,  // 12: akademik.AkademikService.CreateMahasiswa:output_type -> akademik.Mahasiswa
	1,  // 13: akademik.AkademikService.GetMahasiswa:output_type -> akademik.Mahasiswa
	1,  // 14: akademik.AkademikService.UpdateMahasiswa:output_type -> akademik.Mahasiswa
	13, // 15: akademik.AkademikService.DeleteMahasiswa:output_type -> akademik.EmptyResponse
	7,  // 16: akademik.AkademikService.ListMahasiswa:output_type -> akademik.ListMahasiswaResponse
	0,  // 17: akademik.AkademikService.CreateMataKuliah:output_type -> akademik.MataKuliah
	0,  // 18: akademik.AkademikService.GetMataKuliah:output_type -> akademik.MataKuliah
	11, // 19: akademik.AkademikService.ListMataKuliah:output_type -> akademik.ListMataKuliahResponse
	1,  // 20: akademik.AkademikService.DaftarkanMataKuliahUntukMahasiswa:output_type -> akademik.Mahasiswa
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_akademik_proto_init() }
func file_akademik_proto_init() {
	if File_akademik_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_akademik_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MataKuliah); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mahasiswa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMahasiswaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMahasiswaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMahasiswaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMahasiswaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMahasiswaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMahasiswaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMataKuliahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMataKuliahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMataKuliahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMataKuliahResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaftarkanMataKuliahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_akademik_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_akademik_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_akademik_proto_goTypes,
		DependencyIndexes: file_akademik_proto_depIdxs,
		MessageInfos:      file_akademik_proto_msgTypes,
	}.Build()
	File_akademik_proto = out.File
	file_akademik_proto_rawDesc = nil
	file_akademik_proto_goTypes = nil
	file_akademik_proto_depIdxs = nil
}
